<?php

declare(strict_types=1);

namespace RouteForge\Common\Type;

/**
 * TS 类型声明与 JSON 结构生成器（SPEC §3.2 route:forge:types 的输出层）。
 *
 * 框架无关：输入为「层级 → 路由名 → 类型约束」的二维数组，
 * 由各框架命令（Artisan / ThinkPHP Console / Symfony Command）负责收集，
 * 本类只做纯字符串生成。
 *
 * 生成的 d.ts 通过 module augmentation 增强 @route-forge/core 的 ForgeRouteMap，
 * 使前端 composable（useForge / useForgeApi）自动获得路由名和参数的类型推断。
 */
final class TypeGenerator
{
    /** 带 body 的 HTTP 方法（其余 GET/DELETE/HEAD 等视为无 body） */
    private const BODY_METHODS = ['POST', 'PUT', 'PATCH'];

    /**
     * 从 RouteAnalyzer 的 rows 组装「层级 → 路由名 → 类型约束」二维映射
     * （generateDts / generateJson 的直接输入）。
     *
     * 预置全部目标层级（含 0 路由的空层级）：保证 ForgeLevel 联合类型覆盖
     * 所有已配置层级，前端引用「空层级」的路由名不再因类型缺失而 TS 报错。
     *
     * 框架无关：rows 即 RouteAnalyzer::analyze() 的返回行，各框架命令只负责
     * 收集路由并决定目标层级列表（全部已配置层级或 --level 单一层级）。
     *
     * @param list<array{name:string, level:string, tier:?string, methods:string[], uri:string, parameters:string[], parameter_defaults:array<string,mixed>, alias_of:?string}> $rows
     * @param list<string> $targets 目标层级列表
     *
     * @return array<string, array<string, array{method:string, params:string[], optionalParams:string[], defaults:array<string,mixed>, hasBody:bool, response:string}>>
     */
    public function collectTargets(array $rows, array $targets): array
    {
        $routesByLevel = array_fill_keys($targets, []);

        foreach ($rows as $r) {
            // unassigned 路由不生成类型（SPEC §3.2：无层级归属，不进入 ForgeRoutes 映射）；
            // 别名行已由 analyzer 预生成（跟随目标层级），此处统一过滤即可；
            // 非目标层级（--level 过滤）也跳过：未 isset 的键不能隐式创建，
            // 否则过滤后 d.ts 仍会出现 client 等层级块
            if ($r['tier'] === null || !isset($routesByLevel[$r['level']])) {
                continue;
            }

            $methods = array_values(array_filter(
                $r['methods'],
                fn (string $m): bool => strtoupper($m) !== 'HEAD',
            ));
            $method = !empty($methods) ? strtoupper($methods[0]) : 'GET';

            $routesByLevel[$r['level']][$r['name']] = [
                'method'         => $method,
                'params'         => $r['parameters'],
                'optionalParams' => $this->extractOptionalParams($r['uri']),
                'defaults'       => $r['parameter_defaults'],
                'hasBody'        => in_array($method, self::BODY_METHODS, true),
                // response 始终为 unknown（v1.0 不支持自定义响应类型）
                'response'       => 'unknown',
            ];
        }

        return $routesByLevel;
    }

    /**
     * 生成 d.ts 内容（二级映射：层级 → 路由名 → 类型约束）。
     *
     * @param array<string,array<string,array{method:string,params:string[],optionalParams:string[],defaults:array<string,mixed>,hasBody:bool,response:string}>> $routesByLevel
     * @param string $endpointPrefix 实际端点前缀（经与端点注册相同的规范化），写入文件头注释
     */
    public function generateDts(array $routesByLevel, string $endpointPrefix): string
    {
        $timestamp = date('Y-m-d\TH:i:s.000\Z');
        $levels = array_map(fn ($l) => $l === '' ? 'unassigned' : $l, array_keys($routesByLevel));

        $lines      = [];
        $lines[]    = '// AUTO-GENERATED by route:forge:types. Do not edit.';
        $lines[]    = "// 生成时间: {$timestamp}";
        $lines[]    = "// 端点: {$endpointPrefix}";
        $lines[] = 'import { ForgeRouteMap } from "@route-forge/core";';
        $lines[]    = '';
        $lines[]    = '// ─── 层级名联合类型 ───────────────────────────────────────────';
        $levelUnion = empty($levels) ? 'never' : implode(' | ',
            array_map(fn ($l) => "'{$l}'", $levels));
        $lines[]    = "export type ForgeLevel = {$levelUnion};";
        $lines[]    = '';
        $lines[]    = '// ─── 各层级路由名联合类型 ─────────────────────────────────────';
        $lines[] = 'export type ForgeRouteName<L extends ForgeLevel> = L extends keyof ForgeRouteMap';
        $lines[] = '  ? keyof ForgeRouteMap[L] & string';
        $lines[]    = '  : never;';
        $lines[]    = '';
        $lines[] = '// ─── 单条路由元信息（端点返回的 routes 值结构） ────────────────────';
        $lines[] = 'export interface ForgeRouteMeta {';
        $lines[] = '  method: string;';
        $lines[] = '  uri: string;';
        $lines[] = '  parameters: string[];';
        $lines[] = '  parameter_defaults: Record<string, unknown>;';
        $lines[] = '}';
        $lines[] = '';
        $lines[] = '// ─── 按层级 → 路由名 → 类型约束的映射 ────────────────────────';
        $lines[] = '// 通过 module augmentation 增强 @route-forge/core 的 ForgeRouteMap，';
        $lines[] = '// 使 useForge / useForgeApi 自动获得路由名和参数的类型推断。';
        $lines[] = '// ⚠ 依赖 @route-forge/core 包，请确保前端项目已安装该依赖。';
        $lines[]    = '';
        $lines[] = "declare module '@route-forge/core' {";
        $lines[] = '  interface ForgeRouteMap {';

        foreach ($routesByLevel as $level => $routes) {
            $levelKey = $level ?: 'unassigned';
            $lines[]  = "    {$this->quoteKey($levelKey)}: {";
            foreach ($routes as $name => $r) {
                $paramsFields = $this->formatParamsFields($r['params'], $r['optionalParams'],
                    '        ');
                $paramsBlock  = empty($paramsFields)
                    ? '{}'
                    : "{\n" . implode("\n", $paramsFields) . "\n      }";
                $lines[]      = "      {$this->quoteKey($name)}: {";
                $lines[]      = "        method: '{$r['method']}';";
                $lines[]      = "        params: {$paramsBlock};";
                if ($r['hasBody']) {
                    $lines[] = "        body: unknown;";
                }
                $lines[] = "        response: {$r['response']};";
                $lines[] = "      };";
            }
            $lines[] = '    };';
            $lines[] = '';
        }

        $lines[] = '  }';
        $lines[] = '}';
        $lines[] = '';
        $lines[] = '// ─── 本地别名（向后兼容） ──────────────────────────────────────';
        $lines[] = 'export type ForgeRoutes = ForgeRouteMap;';
        $lines[] = '';
        $lines[] = '// ─── 工具类型：从 ForgeRouteMap 提取具体字段 ────────────────────';
        $lines[]    = '';
        $lines[]    = '/** 提取指定层级 + 路由名的 method */';
        $lines[]    = 'export type ForgeMethod<';
        $lines[]    = '  L extends ForgeLevel,';
        $lines[]    = '  N extends ForgeRouteName<L>,';
        $lines[] = '> = L extends keyof ForgeRouteMap';
        $lines[] = "  ? N extends keyof ForgeRouteMap[L] ? ForgeRouteMap[L][N]['method'] : never";
        $lines[] = '  : never;';
        $lines[]    = '';
        $lines[]    = '/** 提取指定层级 + 路由名的路径参数 */';
        $lines[]    = 'export type ForgeParams<';
        $lines[]    = '  L extends ForgeLevel,';
        $lines[]    = '  N extends ForgeRouteName<L>,';
        $lines[] = '> = L extends keyof ForgeRouteMap';
        $lines[] = "  ? N extends keyof ForgeRouteMap[L] ? ForgeRouteMap[L][N]['params'] : never";
        $lines[] = '  : never;';
        $lines[]    = '';
        $lines[]    = '/** 提取指定层级 + 路由名的 body 类型（GET/DELETE 为 never） */';
        $lines[]    = 'export type ForgeBody<';
        $lines[]    = '  L extends ForgeLevel,';
        $lines[]    = '  N extends ForgeRouteName<L>,';
        $lines[] = '> = L extends keyof ForgeRouteMap';
        $lines[] = '  ? N extends keyof ForgeRouteMap[L]';
        $lines[] = "    ? 'body' extends keyof ForgeRouteMap[L][N]";
        $lines[] = "      ? ForgeRouteMap[L][N]['body']";
        $lines[] = '      : never';
        $lines[]    = '    : never';
        $lines[]    = '  : never;';
        $lines[]    = '';
        $lines[]    = '/** 提取指定层级 + 路由名的 response 类型 */';
        $lines[]    = 'export type ForgeResponse<';
        $lines[]    = '  L extends ForgeLevel,';
        $lines[]    = '  N extends ForgeRouteName<L>,';
        $lines[] = '> = L extends keyof ForgeRouteMap';
        $lines[] = "  ? N extends keyof ForgeRouteMap[L] ? ForgeRouteMap[L][N]['response'] : never";
        $lines[] = '  : never;';
        $lines[]    = '';

        return implode("\n", $lines);
    }

    /**
     * 生成 JSON 对象（二级结构：层级 → 路由名）。
     *
     * @param array<string,array<string,array{method:string,params:string[],optionalParams:string[],defaults:array<string,mixed>,hasBody:bool,response:string}>> $routesByLevel
     */
    public function generateJson(array $routesByLevel): string
    {
        $out = [];
        foreach ($routesByLevel as $level => $routes) {
            $levelData = [];
            foreach ($routes as $name => $r) {
                $entry = [
                    'method' => $r['method'],
                    'params' => $r['params'],
                ];
                if (!empty($r['defaults'])) {
                    $entry['parameter_defaults'] = (object) $r['defaults'];
                }
                if ($r['hasBody']) {
                    $entry['body'] = 'unknown';
                }
                $entry['response'] = $r['response'];
                $levelData[$name]  = $entry;
            }
            // (object) 强转：空层级序列化为 {} 而非 []，保持「按路由名索引的对象」契约
            $out[$level ?: 'unassigned'] = (object) $levelData;
        }

        return json_encode($out, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    }

    /**
     * 从 URI 模板中提取可选参数名（{param?} 语法）。
     *
     * 供框架命令在收集阶段调用。
     *
     * @return string[]
     */
    public function extractOptionalParams(string $uri): array
    {
        preg_match_all('/\{(\w+)\?\}/', $uri, $matches);

        return $matches[1] ?? [];
    }

    private function quoteKey(string $name): string
    {
        // 仅在含特殊字符时引号
        if (preg_match('/^[A-Za-z_][A-Za-z0-9_]*$/', $name)) {
            return $name;
        }

        return json_encode($name);
    }

    /**
     * 格式化 params 字段列表
     *
     * TS 类型的 ? 标记基于 URL 模板中参数是否可选（{param?} 语法），
     * 而非是否有默认值。默认值通过 parameter_defaults 独立返回。
     *
     * @param string[] $params
     * @param string[] $optionalParams URL 中可选的参数名列表（{param?} 语法）
     * @param string   $indent
     *
     * @return string[]
     */
    private function formatParamsFields(array $params, array $optionalParams, string $indent): array
    {
        return array_map(function ($p) use ($optionalParams, $indent) {
            $optional = in_array($p, $optionalParams, true) ? '?' : '';

            return "{$indent}{$p}{$optional}: string | number;";
        }, $params);
    }
}
